"{\
  'general':\
  {\
    'name':'jonah',\
    'instance':3,\
    'interval':20000\
  },\
  'components':[\
    {\
      'name':'Analog',\
      'params':'default'\
    },\
    {\
      'name':'Multiplexer',\
      'params':'default'\
     },\
    {\
      'name':'WiFi',\
      'params':['The Promised LAN','jzc2kms77vcmxxa8ptkyj']\
    },\
  ]\
}"
